version: "3"

services:
  mqtt:
    image: toke/mosquitto
    ports:
      - "1883:1883"
    expose:
      - "1883"
  webserver:
    image: php:7-apache
    volumes:
      - "./www:/var/www/html"
    ports:
      - "4242:80"
    links:
      - mqtt
    environment:
      - MQTT_HOST=mqtt
